import "./style.scss";
import { Container, Row, Col, Button, Form } from "react-bootstrap";
import Logo from "../../assests/images/login/logo.png";
function Verification() {
  return <>
  <div>
        <div className="Login_page">
          <Container fluid>
            <Row>
              <Col className=" verification_page">
                <div className="text-center">
                  <img src={Logo} />
                </div>
                <h1>2-Step Verification</h1>
                <p>Enter the verification code generated by your authenticator application</p>
                <Form>
                  <div className="d-flex verification_code">
                    <div>
                      <input />
                    </div>
                    <div>
                      <input />
                    </div><div>
                      <input />
                    </div><div>
                      <input />
                    </div><div>
                      <input />
                    </div><div>
                      <input />
                    </div>
                  </div>
                  

                 
                  <Form.Group className="mb-3" controlId="formBasicCheckbox">
                    <Form.Check type="checkbox" label="Remember this device for 30 days" />
                  </Form.Group>
                  <div className="text-center">
                    <Button variant="primary" type="submit">
                    Verify
                    </Button>
                  </div>
                </Form>
              </Col>
            </Row>
          </Container>
        </div>
      </div></>;
}

export default Verification;
